// @generated
// This file is @generated by prost-build.
/// The top-level message sent by client to <code>CreateS2sPipeline</code> and <code>UpdateS2sPipeline</code> endpoints and received from <code>GetS2sPipeline</code> endpoint.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2sPipeline {
    /// Required. CSI pipeline identifier consisting of S2T, NLU and T2S configuration. ID can be any non-empty string.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Required. S2T pipeline ID, e.g. "german_general"
    #[prost(string, tag="2")]
    pub s2t_pipeline_id: ::prost::alloc::string::String,
    /// Required. NLU project ID, usually a hash, e.g. "ae33586b-x2s2-494a-aa73-1af0589cfc56".
    #[prost(string, tag="3")]
    pub nlu_project_id: ::prost::alloc::string::String,
    /// Required. Language code present in the corresponding NLU project, e.g. "de".
    #[prost(string, tag="4")]
    pub nlu_language_code: ::prost::alloc::string::String,
    /// Required. T2S pipeline ID, e.g. "kerstin".
    #[prost(string, tag="5")]
    pub t2s_pipeline_id: ::prost::alloc::string::String,
}
/// The top-level message sent by client to <code>GetS2sPipeline</code> and <code>DeleteS2sPipeline</code> endpoints.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2sPipelineId {
    /// Required. CSI pipeline identifier.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// The top-level message sent by client to <code>ListS2sPipelines</code> endpoint. Currently without arguments.
///
/// TODO: add filtering options
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListS2sPipelinesRequest {
}
/// The top-level message received from <code>ListS2sPipelines</code> endpoint.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListS2sPipelinesResponse {
    /// Collection of S2S pipelines of the server.
    #[prost(message, repeated, tag="1")]
    pub pipelines: ::prost::alloc::vec::Vec<S2sPipeline>,
}
/// The top-level message sent by the client to the <code>S2sStream</code> method.
/// Multiple request messages should be sent in order:
/// <ul>
///    <li>The first message must contain <code>pipeline_id</code> and can contain <code>session_id</code> or <code>initial_intent_display_name</code>. The message must not contain <code>audio</code> nor <code>end_of_stream</code>.</li>
///    <li>All subsequent messages must contain <code>audio</code>. If <code>end_of_stream</code> is <code>true</code>, the stream is closed.</li>
/// </ul>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2sStreamRequest {
    /// Optional. The CSI pipeline ID specified in the initial request.
    #[prost(string, tag="1")]
    pub pipeline_id: ::prost::alloc::string::String,
    /// <p>Optional. The session or call ID specified in the initial request. It&apos;s up to the API caller to choose an appropriate string. It can be a random number or some type of user identifier (preferably hashed).</p>
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
    /// Optional. The input audio content to be recognized.
    #[prost(bytes="vec", tag="3")]
    pub audio: ::prost::alloc::vec::Vec<u8>,
    /// If <code>true</code>, the recognizer will not return any further hypotheses about this piece of the audio. May only be populated for <code>event_type</code> = <code>RECOGNITION_EVENT_TRANSCRIPT</code>.
    #[prost(bool, tag="4")]
    pub end_of_stream: bool,
    /// Optional. Intent display name to trigger in NLU system in the beginning of the conversation.
    #[prost(string, tag="5")]
    pub initial_intent_display_name: ::prost::alloc::string::String,
}
/// The top-level message returned from the <code>S2sStream</code> method.
/// A response message is returned for each utterance of the input stream. It contains the full response from NLU system in <code>detect_intent_response</code> or the full T2S response in <code>synthesize_response</code>.
/// Multiple response messages can be returned in order:
/// <ul>
///    <li>The first response message for an input utterance contains response from NLU system <code>detect_intent_response</code> with detected intent and N fulfillment messages (N &gt;= 0).</li>
///    <li>The next N response messages contain for each fulfillment message one of the following:
///      <ul>
///        <li>T2S response <code>synthesize_response</code> with synthesized audio</li>
///        <li>SIP trigger message <code>sip_trigger</code> with SIP trigger extracted from the fulfillment message</li>
///      </ul>
///    </li>
/// </ul>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct S2sStreamResponse {
    /// Optional. Identifier of the utterance this response belongs to. All chunks of one synthesized utterance share the same <code>utterance_id</code>
    #[prost(string, tag="4")]
    pub utterance_id: ::prost::alloc::string::String,
    /// Optional. Zero-based index of this chunk within the utterance identified by <code>utterance_id</code>
    #[prost(int32, tag="5")]
    pub chunk_index: i32,
    /// Optional. If <code>true</code>, this is the last chunk of the utterance identified by <code>utterance_id</code>
    #[prost(bool, tag="6")]
    pub last_chunk: bool,
    /// Optional. Monotonic turn epoch of the conversation turn that produced this response. Used by consumers to fence stale audio of an interrupted turn
    #[prost(uint64, tag="7")]
    pub turn_epoch: u64,
    /// Response type for the S2S stream. One of the following will be populated.
    #[prost(oneof="s2s_stream_response::Response", tags="1, 2, 3")]
    pub response: ::core::option::Option<s2s_stream_response::Response>,
}
/// Nested message and enum types in `S2sStreamResponse`.
pub mod s2s_stream_response {
    /// Response type for the S2S stream. One of the following will be populated.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        /// full NLU detect intent response
        #[prost(message, tag="1")]
        DetectIntentResponse(super::super::nlu::DetectIntentResponse),
        /// full T2S synthesize response
        #[prost(message, tag="2")]
        SynthesizeResponse(super::super::t2s::SynthesizeResponse),
        /// SIP trigger message
        #[prost(message, tag="3")]
        SipTrigger(super::SipTrigger),
    }
}
/// SIP trigger message.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipTrigger {
    /// Type of the SIP trigger.
    #[prost(enumeration="sip_trigger::SipTriggerType", tag="1")]
    pub r#type: i32,
    /// extra parameters for the trigger
    #[prost(message, optional, tag="2")]
    pub content: ::core::option::Option<::prost_types::Struct>,
}
/// Nested message and enum types in `SipTrigger`.
pub mod sip_trigger {
    /// Type of SIP trigger that can be executed during a conversation.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum SipTriggerType {
        /// should never be used
        Unspecified = 0,
        /// hard hangup
        Hangup = 1,
        /// handover to human
        HumanHandover = 2,
        /// send now
        SendNow = 3,
        /// pause
        Pause = 4,
        /// transfer
        Transfer = 5,
        /// invite to conference call
        Invite = 6,
        /// play audio
        PlayAudio = 7,
    }
    impl SipTriggerType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "UNSPECIFIED",
                Self::Hangup => "HANGUP",
                Self::HumanHandover => "HUMAN_HANDOVER",
                Self::SendNow => "SEND_NOW",
                Self::Pause => "PAUSE",
                Self::Transfer => "TRANSFER",
                Self::Invite => "INVITE",
                Self::PlayAudio => "PLAY_AUDIO",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSPECIFIED" => Some(Self::Unspecified),
                "HANGUP" => Some(Self::Hangup),
                "HUMAN_HANDOVER" => Some(Self::HumanHandover),
                "SEND_NOW" => Some(Self::SendNow),
                "PAUSE" => Some(Self::Pause),
                "TRANSFER" => Some(Self::Transfer),
                "INVITE" => Some(Self::Invite),
                "PLAY_AUDIO" => Some(Self::PlayAudio),
                _ => None,
            }
        }
    }
}
/// Health checks.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckUpstreamHealthResponse {
    /// Health checks for Speech-2-Text
    #[prost(message, optional, tag="1")]
    pub s2t_status: ::core::option::Option<super::super::google::rpc::Status>,
    /// Health checks for NLU
    #[prost(message, optional, tag="2")]
    pub nlu_status: ::core::option::Option<super::super::google::rpc::Status>,
    /// Health checks for Text-2-Speech
    #[prost(message, optional, tag="3")]
    pub t2s_status: ::core::option::Option<super::super::google::rpc::Status>,
}
/// Control stream message.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ControlStreamRequest {
}
/// Control stream response message.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ControlStreamResponse {
    /// Control status
    #[prost(enumeration="ControlStatus", tag="1")]
    pub control_status: i32,
    /// Monotonic barge-in epoch/sequence number so control status transitions are correlatable with the <code>S2sStreamResponse</code> <code>turn_epoch</code> and a second barge-in during a resumed remainder can never be coalesced away
    #[prost(uint64, tag="2")]
    pub epoch: u64,
}
/// Request to set control status.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetControlStatusRequest {
    /// Control status
    #[prost(enumeration="ControlStatus", tag="1")]
    pub control_status: i32,
}
/// Response of setting the control status with the old and new status objects.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetControlStatusResponse {
    /// Previous 'old' control status
    #[prost(enumeration="ControlStatus", tag="1")]
    pub old_control_status: i32,
    /// Current 'new' control status
    #[prost(enumeration="ControlStatus", tag="2")]
    pub new_control_status: i32,
}
/// A condition message with its type and value.
/// A Condition can be of various types.
/// Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:
/// Immediate execution:
/// <pre><code>
/// {
///     &quot;type&quot;: &quot;immediate&quot;
/// }
/// </code></pre>
/// Number of interactions of the user with the AI agent:
/// <pre><code>
/// {
///     &quot;type&quot;: &quot;interactions&quot;,
///     &quot;value&quot;: &quot;10&quot;
/// }
/// </code></pre>
/// Number of seconds:
/// <pre><code>
/// {
///     &quot;type&quot;: &quot;duration&quot;,
///     &quot;value&quot;: &quot;3600&quot;
/// }
/// </code></pre>
/// At a specific date and time:
/// <pre><code>
/// {
///     &quot;type&quot;: &quot;datetime&quot;,
///     &quot;value&quot;: &quot;2021-12-23T13:45:00.000Z&quot;
/// }
/// </code></pre>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Condition {
    /// Condition type
    #[prost(enumeration="ConditionType", tag="1")]
    pub r#type: i32,
    /// Value of the condition. Examples of conditions values based on the condition type are given in the <code>ConditionType</code> documentation.
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
}
/// Parameters of the control message passed to the service specified in the control message.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControlMessageServiceParameters {
    /// SIP: callee id to transfer call to
    #[prost(string, tag="3")]
    pub transfer_id: ::prost::alloc::string::String,
    /// SIP: bytes of audio files to play to a caller
    #[prost(bytes="vec", repeated, tag="4")]
    pub wav_files: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// text, e.g. for NLU detect intent response or Text-2-Speech voice synthesis
    #[prost(string, tag="5")]
    pub text: ::prost::alloc::string::String,
    /// NLU: context for creating, updating or deleting contextual information from a NLU session
    #[prost(message, optional, tag="6")]
    pub context: ::core::option::Option<super::nlu::Context>,
    /// NLU: the session id of a NLU session
    #[prost(string, tag="7")]
    pub session_id: ::prost::alloc::string::String,
    /// NLU: the name of the context of a NLU session
    #[prost(string, tag="8")]
    pub context_name: ::prost::alloc::string::String,
    /// CSI: the condition that defines when a control message should be executed
    #[prost(message, optional, tag="9")]
    pub condition_start: ::core::option::Option<Condition>,
    /// CSI: the condition that defines when a control message should stop its execution
    #[prost(message, optional, tag="10")]
    pub condition_end: ::core::option::Option<Condition>,
    /// Configuration
    #[prost(oneof="control_message_service_parameters::Config", tags="1, 2")]
    pub config: ::core::option::Option<control_message_service_parameters::Config>,
}
/// Nested message and enum types in `ControlMessageServiceParameters`.
pub mod control_message_service_parameters {
    /// Configuration
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Config {
        /// Text-2-Speech: configuration to control the synthesis of a text into audio
        #[prost(message, tag="1")]
        T2sConfig(super::super::t2s::RequestConfig),
        /// Speech-2-Text: configuration to control the recognition of text based on human voice audio
        #[prost(message, tag="2")]
        S2tConfig(super::super::s2t::TranscribeRequestConfig),
    }
}
/// A control message.
/// Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:
/// <pre><code>
/// {
///    &quot;service&quot;: &quot;&lt;SERVICE_NAME&gt;&quot;, 			// e.g. ondewo_s2t
///    &quot;method&quot;: &quot;&lt;SERVICE_CONTROL_METHOD&gt;&quot;, 	// e.g. update_config
///    &quot;parameters&quot;: [
///        // primitive data types and JSON objects are possible
///        1,
///        1.0,
///        -2.0,
///        &quot;string&quot;,
///        true,
///    	 {
///            // parameter JSON object
///        },
///        {
///            // Condition start object
///        },
///        {
///            // Condition end object \[optional\]
///        },
///     ]
/// }
/// </code></pre>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ControlMessage {
    /// Service to control. Valid service names are: <code>ondewo_nlu</code>, <code>ondewo_t2s</code>, <code>ondewo_s2t</code>, <code>ondewo_sip</code> and <code>ondewo_csi</code>.
    #[prost(enumeration="ControlMessageServiceName", tag="1")]
    pub service: i32,
    /// Method to invoke on the service
    #[prost(enumeration="ControlMessageServiceMethod", tag="2")]
    pub method: i32,
    /// Parameters to use to invoke the method of the service
    #[prost(message, optional, tag="3")]
    pub parameters: ::core::option::Option<ControlMessageServiceParameters>,
}
/// Control status.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ControlStatus {
    /// Status that control stream is ok
    Ok = 0,
    /// Status that control stream needs to stop immediately
    EmergencyStop = 1,
    /// Status that voice activity detection detected start of speech
    VadStartOfSpeech = 2,
    /// Status that the caller started speaking while the bot was speaking (barge-in): playback pauses and the un-played audio remainder is buffered
    BargeIn = 3,
    /// Status sent by the server to the client to resume playback of the buffered audio remainder after a false interruption (no committed transcription final arrived within the false interruption timeout)
    ResumePlayback = 4,
    /// Status sent by the server to the client to discard the buffered audio remainder because the interruption committed as a real turn
    DiscardRemainder = 5,
    /// Status reported by the client to the server via <code>SetControlStatus</code> that playback of the buffered audio remainder has resumed
    PlaybackResumed = 6,
    /// Status reported by the client to the server via <code>SetControlStatus</code> that playback of an utterance has completed
    PlaybackDone = 7,
    /// Status reported by ondewo-sip to the server via <code>SetControlStatus</code> that the phone call has ENDED and the server must reset ALL per-call state in place (persistent-listener model). It is a command, not a state: it is never pushed onto the control stream
    CallEnded = 8,
}
impl ControlStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Ok => "OK",
            Self::EmergencyStop => "EMERGENCY_STOP",
            Self::VadStartOfSpeech => "VAD_START_OF_SPEECH",
            Self::BargeIn => "BARGE_IN",
            Self::ResumePlayback => "RESUME_PLAYBACK",
            Self::DiscardRemainder => "DISCARD_REMAINDER",
            Self::PlaybackResumed => "PLAYBACK_RESUMED",
            Self::PlaybackDone => "PLAYBACK_DONE",
            Self::CallEnded => "CALL_ENDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OK" => Some(Self::Ok),
            "EMERGENCY_STOP" => Some(Self::EmergencyStop),
            "VAD_START_OF_SPEECH" => Some(Self::VadStartOfSpeech),
            "BARGE_IN" => Some(Self::BargeIn),
            "RESUME_PLAYBACK" => Some(Self::ResumePlayback),
            "DISCARD_REMAINDER" => Some(Self::DiscardRemainder),
            "PLAYBACK_RESUMED" => Some(Self::PlaybackResumed),
            "PLAYBACK_DONE" => Some(Self::PlaybackDone),
            "CALL_ENDED" => Some(Self::CallEnded),
            _ => None,
        }
    }
}
/// Control message services.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ControlMessageServiceName {
    /// Unknown control message service name
    Unknownname = 0,
    /// Speech-2-Text control message service name
    OndewoS2t = 1,
    /// Text-2-Speech control message service name
    OndewoT2s = 2,
    /// NLU control message service name
    OndewoNlu = 3,
    /// SIP control message service name
    OndewoSip = 4,
    /// VTSI control message service name
    OndewoVtsi = 5,
    /// CSI control message service name
    OndewoCsi = 6,
    /// Survey control message service name
    OndewoSurvey = 7,
}
impl ControlMessageServiceName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknownname => "UNKNOWNNAME",
            Self::OndewoS2t => "ondewo_s2t",
            Self::OndewoT2s => "ondewo_t2s",
            Self::OndewoNlu => "ondewo_nlu",
            Self::OndewoSip => "ondewo_sip",
            Self::OndewoVtsi => "ondewo_vtsi",
            Self::OndewoCsi => "ondewo_csi",
            Self::OndewoSurvey => "ondewo_survey",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWNNAME" => Some(Self::Unknownname),
            "ondewo_s2t" => Some(Self::OndewoS2t),
            "ondewo_t2s" => Some(Self::OndewoT2s),
            "ondewo_nlu" => Some(Self::OndewoNlu),
            "ondewo_sip" => Some(Self::OndewoSip),
            "ondewo_vtsi" => Some(Self::OndewoVtsi),
            "ondewo_csi" => Some(Self::OndewoCsi),
            "ondewo_survey" => Some(Self::OndewoSurvey),
            _ => None,
        }
    }
}
/// Control message methods to control services during a conversation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ControlMessageServiceMethod {
    /// Unknown method (default)
    Unknownmethod = 0,
    /// CSI: update configuration
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_s2t&quot;,
    ///     &quot;method&quot;: &quot;update_config&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    ///             // Speech2TextConfig object
    ///             &quot;s2tPipelineId&quot; : &quot;s2t_pipeline_german_1&quot;,
    ///             &quot;languageModelName&quot; : &quot;language_model_german&quot;
    ///         },
    ///         {
    ///              // condition_start object =&gt; should take effect immediately
    ///              &quot;type&quot;: &quot;immediate&quot;,
    ///              &quot;value&quot;: &quot;0&quot;
    ///         },
    ///         {
    ///              // condition_end object - s2t config will be changed back to
    ///              // last valid configuration after 10 interactions of user with
    ///              // the AI agent
    ///              &quot;type&quot;: &quot;interactions&quot;,
    /// 	           &quot;value&quot;: 10
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    UpdateConfig = 1,
    /// CSI: undo previous configuration update
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_s2t&quot;,
    ///     &quot;method&quot;: &quot;undo_config&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    /// 	          // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    UndoConfig = 2,
    /// CSI: reset configuration to default
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_s2t&quot;,
    ///     &quot;method&quot;: &quot;reset_config&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    ResetConfig = 3,
    /// SIP: end conversation / hang up call
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_sip&quot;,
    ///     &quot;method&quot;: &quot;end_call&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    EndCall = 4,
    /// SIP: transfer call
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_sip&quot;,
    ///     &quot;method&quot;: &quot;transfer_call&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      &quot;transfer_id&quot;: &quot;+43123456789@127.0.0.10:5060&quot;,
    ///         },
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    TransferCall = 5,
    /// SIP: play wav files on the call
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_sip&quot;,
    ///     &quot;method&quot;: &quot;play_wav_files&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      &quot;wav_files&quot;:  [
    ///                 &lt;bytes_of_file_1&gt;,
    ///                 &lt;bytes_of_file_2&gt;,
    ///                 &lt;bytes_of_file_3&gt;,
    ///             ]
    ///         },
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty “{}”
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    PlayWavFiles = 6,
    /// SIP: play a certain text on the phone based on Text-2-Speech synthesis
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_sip&quot;,
    ///     &quot;method&quot;: &quot;play_text&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      &quot;text&quot;: &quot;Welcome from ONDEWO AI Agent! How are you today?&quot;,
    ///         },
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    PlayText = 7,
    /// SIP: mute microphone
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_sip&quot;,
    ///     &quot;method&quot;: &quot;mute&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    Mute = 8,
    /// SIP: unmute microphone
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_sip&quot;,
    ///     &quot;method&quot;: &quot;un_mute&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    UnMute = 9,
    /// CSI: stop the execution of all running and scheduled control messages
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;&quot;,    &lt;= empty string since it is for all services / no specific service
    ///     &quot;method&quot;: &quot;stop_all_control_messages&quot;,
    ///     "parameters": [
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty “{}”
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    StopAllControlMessages = 10,
    /// NLU: train agent
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_nlu&quot;,
    ///     &quot;method&quot;: &quot;train_agent&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    TrainAgent = 11,
    /// NLU: cancel the ongoing agent
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_nlu&quot;,
    ///     &quot;method&quot;: &quot;cancel_train_agent&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    CancelTrainAgent = 12,
    /// NLU: delete session and all session-related information
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_nlu&quot;,
    ///     &quot;method&quot;: &quot;delete_session&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
    ///         },
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    DeleteSession = 13,
    /// NLU: delete all context information in the current session
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_nlu&quot;,
    ///     &quot;method&quot;: &quot;delete_all_contexts&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
    ///         },
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    DeleteAllContexts = 14,
    /// NLU: create a context based on the provided contextual information in the current session
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     "service": "ondewo_nlu",
    ///     "method": "create_context",
    ///     "parameters": [
    ///         {
    /// 	 	      &quot;context&quot;: {           &lt;== &lt;NLU Context Object as JSON object&gt;
    ///                 &quot;name&quot;: &quot;projects/db46dcf8-2d2c-4115-ac38-eff443ea0e72/agent/sessions/ss2ea1a20-0784-442b-93c0-eb9e2469420e/contexts/78ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
    ///                 ...,
    ///             }
    ///         },
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty “{}”
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    CreateContext = 15,
    /// NLU: update an existing context based on the provided contextual information in the current session
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     "service": "ondewo_nlu",
    ///     "method": "update_context",
    ///     "parameters": [
    ///         {
    /// 	 	      &quot;context&quot;: {           &lt;== &lt;NLU Context Object as JSON object&gt;
    ///                 &quot;name&quot;: &quot;projects/db46dcf8-2d2c-4115-ac38-eff443ea0e72/agent/sessions/2dea1a20-0784-442b-93c0-eb9e2469420e/contexts/78ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
    ///                 ...,
    ///             }
    ///         },
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty “{}”
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    UpdateContext = 16,
    /// NLU: delete an existing context including all contextual information in the current session
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_nlu&quot;,
    ///     &quot;method&quot;: &quot;delete_context&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
    /// 	 	      &quot;context_name&quot;: &quot;78ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
    ///         },
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    DeleteContext = 17,
    /// NLU: execute a detect intent request based on the provided information in the current session
    ///
    /// <p>Example of a JSON how to invoke a control message via ONDEWO RABBITMQ service:</p>
    /// <pre><code>
    /// {
    ///     &quot;service&quot;: &quot;ondewo_nlu&quot;,
    ///     &quot;method&quot;: &quot;detect_intent&quot;,
    ///     &quot;parameters&quot;: [
    ///         {
    /// 	 	      &quot;session_id&quot;: &quot;97ea1a20-0784-442b-93c0-eb9e2469420e&quot;,
    /// 	 	      &quot;text&quot;: &quot;Are you an artificial intelligence?&quot;,
    ///         },
    ///         {
    /// 	 	      // condition_start object
    ///         },
    ///         {
    /// 	 	      // condition_end object (OPTIONAL) - for permanent change
    ///             // no condition_end needs to be supplied i.e.
    /// 		      // this parameter is missing or empty &quot;{}&quot;
    ///         },
    ///     ]
    /// }
    /// </code></pre>
    DetectIntent = 18,
}
impl ControlMessageServiceMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknownmethod => "UNKNOWNMETHOD",
            Self::UpdateConfig => "update_config",
            Self::UndoConfig => "undo_config",
            Self::ResetConfig => "reset_config",
            Self::EndCall => "end_call",
            Self::TransferCall => "transfer_call",
            Self::PlayWavFiles => "play_wav_files",
            Self::PlayText => "play_text",
            Self::Mute => "mute",
            Self::UnMute => "un_mute",
            Self::StopAllControlMessages => "stop_all_control_messages",
            Self::TrainAgent => "train_agent",
            Self::CancelTrainAgent => "cancel_train_agent",
            Self::DeleteSession => "delete_session",
            Self::DeleteAllContexts => "delete_all_contexts",
            Self::CreateContext => "create_context",
            Self::UpdateContext => "update_context",
            Self::DeleteContext => "delete_context",
            Self::DetectIntent => "detect_intent",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWNMETHOD" => Some(Self::Unknownmethod),
            "update_config" => Some(Self::UpdateConfig),
            "undo_config" => Some(Self::UndoConfig),
            "reset_config" => Some(Self::ResetConfig),
            "end_call" => Some(Self::EndCall),
            "transfer_call" => Some(Self::TransferCall),
            "play_wav_files" => Some(Self::PlayWavFiles),
            "play_text" => Some(Self::PlayText),
            "mute" => Some(Self::Mute),
            "un_mute" => Some(Self::UnMute),
            "stop_all_control_messages" => Some(Self::StopAllControlMessages),
            "train_agent" => Some(Self::TrainAgent),
            "cancel_train_agent" => Some(Self::CancelTrainAgent),
            "delete_session" => Some(Self::DeleteSession),
            "delete_all_contexts" => Some(Self::DeleteAllContexts),
            "create_context" => Some(Self::CreateContext),
            "update_context" => Some(Self::UpdateContext),
            "delete_context" => Some(Self::DeleteContext),
            "detect_intent" => Some(Self::DetectIntent),
            _ => None,
        }
    }
}
/// Type of condition that need to be satisfied to execute a control message.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConditionType {
    /// Unknown type
    Unknowtype = 0,
    /// Immediate execution of the control message. Example value need be given as a string in the format: <pre><code>value=&quot;5&quot;</code></pre>
    Immediate = 1,
    /// Duration in number of seconds after a control message should be executed. Example value need be given as a string in the format: <pre><code>value=&quot;10&quot;</code></pre>
    Duration = 2,
    /// Date and time when a control message should be executed. Example value need be given as a string in the format: <pre><code>value=&quot;2021-12-23T13:45:00.000Z&quot;</code></pre>
    Datetime = 3,
    /// Number of interactions of the user with an ONDEWO AI agent after a control message should be executed. Example value need be given as a string in the format: <pre><code>value=&quot;4&quot;</code></pre>
    Interactions = 4,
}
impl ConditionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknowtype => "UNKNOWTYPE",
            Self::Immediate => "immediate",
            Self::Duration => "duration",
            Self::Datetime => "datetime",
            Self::Interactions => "interactions",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWTYPE" => Some(Self::Unknowtype),
            "immediate" => Some(Self::Immediate),
            "duration" => Some(Self::Duration),
            "datetime" => Some(Self::Datetime),
            "interactions" => Some(Self::Interactions),
            _ => None,
        }
    }
}
include!("ondewo.csi.tonic.rs");
// @@protoc_insertion_point(module)
